language:
- c
addons:
  apt_packages:
os:
- linux
- osx
compiler:
- gcc
script:
- "./build-x86-64.sh"
before_deploy:
- rm $TRAVIS_BUILD_DIR/tls-scan
- mkdir -p $TRAVIS_BUILD_DIR/tls-scan/man/man1
- cp $TRAVIS_BUILD_DIR/build-root/bin/tls-scan $TRAVIS_BUILD_DIR/tls-scan/tls-scan
- cp $TRAVIS_BUILD_DIR/build-root/share/man/man1/tls-scan.1.gz $TRAVIS_BUILD_DIR/tls-scan/man/man1/tls-scan.1.gz
- cp $TRAVIS_BUILD_DIR/build-root/etc/tls-scan/ca-bundle.crt $TRAVIS_BUILD_DIR/tls-scan/ca-bundle.crt
- tar -zcvf tls-scan-${TRAVIS_OS_NAME}.tar.gz ./tls-scan/
deploy:
  provider: releases
  api_key:
    secure: n2QhVYiWUZqNxx/jmq4rCLgEjZYvr5M6I6fZ5/Sr4aCIOlIRNtrm1Z+cmUxmrEoP3TCmFHXOWV1kjTKSphVZDPzOlFALaY4VMUoTUCNwcVMTrYAgYnaLagXozGDEkWqYcGvyTXir1PQ9+Yk1dkUqbHgHV1BmccYSO97tBQkFcAGMdpcqto0pjQsbf554ILtjZF4ssCyDQNYLeWsuA8tF0pnEwJgUlQDpPn861vAaqInw/DvoKlGfkKWznoiYifpI0R1XqfdYdCmf/X/gqgfBkcHox6E0Q293SLbNLJUVtO1pfozurj+bQopHZ6+I4oaS8G/MxlH0TO/63pEu/TY/VE4OKdMFu/3zJFmpChvA+RFH2/fkAcqgx6yOIHFj0R3XONRSUU0coAxgfm9MS6DbrluquqYIl+7uTyAvWrq84r1Ef4Yd4MgCiIqMfqcA78sRqW9o9/e5EGsrKNpX8HgSriCN4KziOauqf1mhVgiM1eeY10h6onA1Pw1nemx9R++jpET4frIU0VNNBYMn5gdhQr7vxcROs0GmGpmG8B1/a8kjlTWCnD3ZdWo+YAJ1gd3UeosHaJyOmvlOmFP9x1/EvYjVgluC3+WS/+F6f/l/NKfWenzG5wXCu4fKYpyRJcPM5IeOyd1OqFRzzsoB/Toc1m/k44/Mu3POTFS096CsTw8=
  file: tls-scan-$TRAVIS_OS_NAME.tar.gz
  skip_cleanup: true
  on:
    repo: prbinu/tls-scan
    tags: true
